import type { NextPage } from "next";
import Head from "next/head";
import Authorized from "@/src/shared/components/layout/Authorized";
import { LangContext } from "src/shared/context/LanguageContext";
import React, { FC, useContext } from "react";
import { useGetUser } from "src/shared/auth/UserProvider";
import Userlist from "src/admin/userlist";
import Dashboard from "src/dashboard";
import { useUserLoginOrNot } from "src/shared/auth/useRedirectOnToken";
import Userrole from "src/shared/hooks/userrole";

const Home: NextPage = () => {
  const {
    dispatch: { translate },
  } = useContext(LangContext);
  const user = useGetUser();
  useUserLoginOrNot();
  const [role] = Userrole();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"
        />

        <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
      </Head>
      <div className="w-full text-center h-full">
        <Authorized translate={translate}>
          {role === "admin" ? (
            <div>
              <Userlist />{" "}
            </div>
          ) : role === "client" ? (
            <div>
              <Dashboard />
            </div>
          ) : null}
        </Authorized>
      </div>
    </>
  );
};

export default Home;
